CREATE TABLE IF NOT EXISTS tu_export_template (
    id VARCHAR(32) PRIMARY KEY COMMENT '模板ID',
    name VARCHAR(100) NOT NULL COMMENT '模板名称',
    type VARCHAR(50) DEFAULT 'docx' COMMENT '模板类型',
    config JSON NOT NULL COMMENT '样式配置（JSON）',
    is_default TINYINT DEFAULT 0 COMMENT '是否默认: 0=否 1=是',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除: 0=否 1=是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文章导出模板配置表';

-- 内置 12 套预设模板（与 full-prototype-v20.html 保持一致）
INSERT INTO tu_export_template(id, name, type, config, is_default, is_deleted, created_at, updated_at) VALUES
('tpl_gh_std', '公众号标准模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 14,
  "bodyColor": "#262626",
  "headingColor": "#1a1a1a",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 200,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#f6ffed",
  "previewColor": "#07c160",
  "description": "16px 正文 / 18px 小标题 / 绿色强调"
}', 1, 0, NOW(), NOW()),
('tpl_toutiao', '今日头条模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 13,
  "headingFontSizePt": 14,
  "bodyColor": "#222222",
  "headingColor": "#ff6600",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 200,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1440,
  "marginRight": 1440,
  "quoteBg": "#fff7e6",
  "previewColor": "#ff6600",
  "description": "17px 正文 / 橙色强调 / 资讯感标题"
}', 0, 0, NOW(), NOW()),
('tpl_xiaohongshu', '小红书图文模板', 'docx', '{
  "fontFamily": "PingFang SC",
  "headingFontFamily": "PingFang SC",
  "bodyFontSizePt": 11,
  "headingFontSizePt": 13,
  "bodyColor": "#333333",
  "headingColor": "#ff2442",
  "lineSpacing": 444,
  "paragraphSpacingAfter": 200,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1440,
  "marginRight": 1440,
  "quoteBg": "#fff0f3",
  "previewColor": "#ff2442",
  "description": "15px 正文 / 粉红标签 / 轻松活泼"
}', 0, 0, NOW(), NOW()),
('tpl_baijiahao', '百家号模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 14,
  "bodyColor": "#262626",
  "headingColor": "#1677ff",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 180,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1440,
  "marginRight": 1440,
  "quoteBg": "#e6f4ff",
  "previewColor": "#1677ff",
  "description": "16px 正文 / 蓝色层级 / 信息密度高"
}', 0, 0, NOW(), NOW()),
('tpl_business', '简约商务模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 11,
  "headingFontSizePt": 12,
  "bodyColor": "#262626",
  "headingColor": "#1677ff",
  "lineSpacing": 420,
  "paragraphSpacingAfter": 180,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#f0f5ff",
  "previewColor": "#1677ff",
  "description": "14px 正文 / 深蓝标题 / 清晰层级"
}', 0, 0, NOW(), NOW()),
('tpl_marketing', '营销转化模板', 'docx', '{
  "fontFamily": "PingFang SC",
  "headingFontFamily": "PingFang SC",
  "bodyFontSizePt": 14,
  "headingFontSizePt": 15,
  "bodyColor": "#262626",
  "headingColor": "#cf1322",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 220,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1440,
  "marginRight": 1440,
  "quoteBg": "#fff2f0",
  "previewColor": "#cf1322",
  "description": "18px 正文 / 红色强调 / 引导行动"
}', 0, 0, NOW(), NOW()),
('tpl_story', '故事叙事模板', 'docx', '{
  "fontFamily": "Georgia",
  "headingFontFamily": "Georgia",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 14,
  "bodyColor": "#262626",
  "headingColor": "#5a3e2b",
  "lineSpacing": 444,
  "paragraphSpacingAfter": 220,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#faf5ef",
  "previewColor": "#8b5e34",
  "description": "16px 正文 / 暖棕标题 / 沉浸阅读"
}', 0, 0, NOW(), NOW()),
('tpl_academic', '学术报告模板', 'docx', '{
  "fontFamily": "宋体",
  "headingFontFamily": "黑体",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 13,
  "bodyColor": "#262626",
  "headingColor": "#1a1a1a",
  "lineSpacing": 360,
  "paragraphSpacingAfter": 160,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#fafafa",
  "previewColor": "#333333",
  "description": "宋体 / 1.5 倍行距 / 自动编号"
}', 0, 0, NOW(), NOW()),
('tpl_magazine', '杂志大字模板', 'docx', '{
  "fontFamily": "Georgia",
  "headingFontFamily": "Georgia",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 14,
  "bodyColor": "#262626",
  "headingColor": "#1a1a1a",
  "lineSpacing": 456,
  "paragraphSpacingAfter": 240,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#fafafa",
  "previewColor": "#1a1a1a",
  "description": "大标题居中 / 衬线字体 / 留白呼吸"
}', 0, 0, NOW(), NOW()),
('tpl_card', '卡片分块模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 11,
  "headingFontSizePt": 13,
  "bodyColor": "#262626",
  "headingColor": "#07c160",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 200,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1440,
  "marginRight": 1440,
  "quoteBg": "#ffffff",
  "previewColor": "#07c160",
  "description": "分块卡片 / 阴影层级 / 信息聚焦"
}', 0, 0, NOW(), NOW()),
('tpl_checklist', '极简清单模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 11,
  "headingFontSizePt": 13,
  "bodyColor": "#262626",
  "headingColor": "#07c160",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 180,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#f6ffed",
  "previewColor": "#07c160",
  "description": "清单体 / 勾选符号 / 行动导向"
}', 0, 0, NOW(), NOW()),
('tpl_dark', '深色沉浸模板', 'docx', '{
  "fontFamily": "微软雅黑",
  "headingFontFamily": "微软雅黑",
  "bodyFontSizePt": 12,
  "headingFontSizePt": 14,
  "bodyColor": "#f0f0f0",
  "headingColor": "#95de64",
  "lineSpacing": 432,
  "paragraphSpacingAfter": 200,
  "marginTop": 1440,
  "marginBottom": 1440,
  "marginLeft": 1800,
  "marginRight": 1800,
  "quoteBg": "#333333",
  "previewColor": "#07c160",
  "description": "深色背景 / 高对比 / 沉浸阅读"
}', 0, 0, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    type = VALUES(type),
    config = VALUES(config),
    is_default = VALUES(is_default),
    is_deleted = VALUES(is_deleted),
    updated_at = NOW();
